sudo: required
services:
  - docker

script:
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
  - echo "TRAVIS_BRANCH=$TRAVIS_BRANCH, PR=$PR, BRANCH=$BRANCH"
  - cd docker
  - docker build -t auroraprj/auroraprj .
  - cd ..
  - docker-compose up -d
  - docker-compose exec drupal /aurora_init.sh --branch $BRANCH
  - docker-compose exec drupal /aurora_test.sh --branch $BRANCH

notifications:
  email:
    - j.carmona.n@gmail.com
