sudo: required
services:
  - docker

script:
  - cd docker
  - docker build -t auroraprj/auroraprj .
  - cd ..
  - docker-compose up -d
  - docker-compose exec drupal /aurora_init.sh --branch $TRAVIS_COMMIT
  - docker-compose exec drupal /aurora_test.sh --branch $TRAVIS_COMMIT

notifications:
  email:
    - j.carmona.n@gmail.com
