sudo: required

language: php

php:
  - nightly

services:
  - docker

install:
  - cd docker
  - docker build -t auroraprj/auroraprj .
  - cd ..
  - mkdir docker_data
  - mkdir docker_data/drupal_data
  - mkdir docker_data/mariadb_data
  - mkdir docker_data/aurora_config
  - mkdir docker_data/aurora_tests

before_script:
  - docker-compose up -d

script:
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
  - echo "TRAVIS_BRANCH=$TRAVIS_BRANCH, PR=$PR, BRANCH=$BRANCH"
  - docker-compose exec drupal /aurora_init.sh --branch $BRANCH
  - docker-compose exec drupal /aurora_test.sh --branch $BRANCH

after_failure:
  - docker-compose logs

notifications:
  email:
    - j.carmona.n@gmail.com
