sudo: required

language: php

php:
  - nightly

services:
  - docker

install:
  - cd docker
  - docker build -t auroraprj/auroraprj .
  - cd ..
  - mkdir docker_data
  - mkdir docker_data/drupal_data
  - mkdir docker_data/mariadb_data
  - mkdir docker_data/aurora_config
  - mkdir docker_data/aurora_tests
  - chown 1001:1001 -R ./docker_data

before_script:
  # posible solución para issue #12 --> ver https://stackoverflow.com/a/45244373
  - docker-compose run --user="root" --entrypoint chown mariadb  -R 1001 /bitnami
  - docker-compose up -d

script:
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
  - echo "TRAVIS_BRANCH=$TRAVIS_BRANCH, PR=$PR, BRANCH=$BRANCH"
  - docker-compose exec drupal /aurora_init.sh --branch $BRANCH
  - docker-compose exec drupal /aurora_test.sh --branch $BRANCH

after_failure:
  - ls -lrt
  - ls -lrt docker_data
  - docker-compose logs

notifications:
  email:
    - j.carmona.n@gmail.com
